---
# tasks file for ntp
- name: make sure chrony is installed
  ansible.builtin.package:
    name: chrony
    state: present
- name: ntp configuration
  ansible.builtin.template: 
    src: chrony.j2
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
  notify: restart chrony daemon
- name: set timezone
  community.general.timezone:
    name: "Europe/Istanbul"