- hosts: test
  vars:
    employee1:
      name: Maya
      job: Developer
      skill: Advanced
  tasks:
  - name: transform dictionary into a list
    template:
      src:  filter.j2
      dest: /tmp/filter.out