- name: host_pinned demo
  hosts: test
  gather_facts: false
  strategy: linear
  #serial: 2
  tasks:
    - command: sleep 1
      register: result
    - name: deneme debug
      debug:
        msg: "{{ inventory_hostname }} task1
              {{ result.start }} - {{ result.end }}"
    - name: debug 1
      debug:
        msg: "A:{{ inventory_hostname }}
              {{ lookup('pipe', 'date +%H-%M-%S') }}
              started"
    - wait_for:
        timeout: "{{ wait_timeout }}"
    - name: debug 2
      debug:
        msg: "A:{{ inventory_hostname }}
              {{ lookup('pipe', 'date +%H-%M-%S') }}
              finished"