---
- hosts: centos2
  become: yes
  roles:
  - apache
  - mysql
  tasks: 
    - name: install script with db connectivity
      copy:
        src: db.php
        dest: "{{ apache_document_root_path }}db.php"
        mode: 0775
